language: node_js
node_js:
  - "14"
  addons:
    chrome: stable
  sudo: required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
